name: JS Actions

on:
  pull_request:
    types: [labeled]

jobs:
  action:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v1
      with:
        node-version: '12'

    - run: npm install

    - name: hello-action
      uses: ./.github/actions/hello-world

    - name: ha-ha
      uses: ./.github/actions/joke-action
